# Generated by Django 5.2.3 on 2025-06-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmleads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(default='temp-lead-id', max_length=100, unique=True),
        ),
    ]
